version: '3.8'

services:
  app:
    build: .
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8080:8080"
    expose:
      - 8000
      - 8080
    # command: sh -c "pipenv install --system && python manage.py runserver 0.0.0.0:8000"
