# Generated by Django 4.2 on 2024-05-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
