# Generated by Django 4.2 on 2024-06-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='comment',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='備考欄'),
        ),
    ]
