# Generated by Django 4.2 on 2024-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedmember',
            name='role',
            field=models.CharField(choices=[('free_role', 'ロール自由'), ('tank', 'タンク'), ('damage', 'ダメージ'), ('support', 'サポート')], default='free_role', max_length=16),
        ),
    ]
