# Generated by Django 4.2 on 2024-05-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Game_Player',
        ),
        migrations.CreateModel(
            name='Favorite_Game_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwin.game_player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
