# Generated by Django 4.2 on 2024-05-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0002_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
