# Generated by Django 4.2 on 2024-06-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0002_alter_recruitment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='comment',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='コメント'),
        ),
    ]
