# Generated by Django 4.2 on 2024-06-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0003_alter_recruitment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedmember',
            name='is_approveis_approved',
            field=models.BooleanField(default=False),
        ),
    ]
