# Generated by Django 4.2 on 2024-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0003_player_favorite_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_players',
            field=models.ManyToManyField(related_name='favorited_by', to='overwin.player'),
        ),
        migrations.DeleteModel(
            name='Favorite_Players',
        ),
    ]
