# Generated by Django 4.2 on 2024-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0003_remove_user_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Player',
            new_name='GamePlayer',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_game_player',
            field=models.ManyToManyField(blank=True, to='overwin.gameplayer'),
        ),
        migrations.DeleteModel(
            name='Favorite_Game_Player',
        ),
    ]
