# Generated by Django 4.2 on 2024-05-14 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0004_rename_game_player_gameplayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_game_player',
        ),
        migrations.CreateModel(
            name='FavoriteGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwin.gameplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
