# Generated by Django 4.2 on 2024-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0004_user_favorite_players_delete_favorite_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_players',
        ),
        migrations.AddField(
            model_name='player',
            name='favorite_players',
            field=models.ManyToManyField(related_name='favorited_by', to='overwin.player'),
        ),
    ]
