# Generated by Django 4.2 on 2024-06-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0004_joinedmember_is_approveis_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinedmember',
            old_name='is_approveis_approved',
            new_name='is_approved',
        ),
    ]
