# Generated by Django 4.2 on 2024-06-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0005_rename_is_approveis_approved_joinedmember_is_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinedMember',
            new_name='JoinMember',
        ),
    ]
