# Generated by Django 4.2 on 2024-05-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0005_remove_user_favorite_game_player_favoritegameplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritegameplayer',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwin.gameplayer', to_field='battle_tag'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='battle_tag',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
