# Generated by Django 4.2 on 2024-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0006_rename_joinedmember_joinmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinmember',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
