# Generated by Django 4.2 on 2024-05-21 05:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0006_alter_favoritegameplayer_game_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_recruit_member', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('tank_role_num', models.IntegerField(null=True)),
                ('damage_role_num', models.IntegerField(null=True)),
                ('support_role_num', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('tank', 'Tank'), ('damage', 'Damage'), ('support', 'Support')], default=None, max_length=16, null=True)),
                ('join_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwin.recruitment')),
            ],
        ),
    ]
