# Generated by Django 4.2 on 2024-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0007_recruitment_joinedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='current_member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
