# Generated by Django 4.2 on 2024-05-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwin', '0008_recruitment_current_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedmember',
            name='role',
            field=models.CharField(blank=True, choices=[('tank', 'タンク'), ('damage', 'ダメージ'), ('support', 'サポート')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='damage_role_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='support_role_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='tank_role_num',
            field=models.IntegerField(default=0),
        ),
    ]
